name: Docker Build and Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libgeos-dev libproj-dev proj-data proj-bin
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Check for critical syntax errors only
        flake8 . --count --select=E9,F63,F7 --show-source --statistics || true
        echo "✅ Syntax check complete (warnings allowed for application code)"
      continue-on-error: true
    
    - name: Test data loading
      run: |
        python -c "import pandas as pd; df = pd.read_csv('storms.csv'); print(f'✅ Loaded {len(df)} records')"
    
    - name: Build Docker image
      run: |
        docker build -t gulf-coast-hurricane-vis:test .
    
    - name: Test Docker image
      run: |
        docker run --rm gulf-coast-hurricane-vis:test python3 -c "import customtkinter; import matplotlib; import cartopy; print('✅ All imports successful')"

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install analysis tools
      run: |
        pip install black isort pylint
      continue-on-error: true
    
    - name: Check code formatting with Black
      run: |
        black --check --diff .
      continue-on-error: true
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
      continue-on-error: true
